-- Grok tutor conversation history.
--
-- The OpenAI Assistants API stored conversation threads server-side; Grok
-- (chat-completions) is stateless, so institute now persists tutor turns here
-- and replays them each request (see server/utilities/grokTutor.js).
--
-- thread_id matches the existing ai_*_tutor_threads.thread_id values (now local
-- UUIDs generated by the app, not OpenAI thread ids).

CREATE TABLE IF NOT EXISTS ai_tutor_messages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    thread_id VARCHAR(64) NOT NULL,
    role VARCHAR(16) NOT NULL,            -- 'user' | 'assistant' | 'system'
    content MEDIUMTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_ai_tutor_messages_thread (thread_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
