<script>
/**
 * Public landing page ("home") — shown to logged-out visitors at /.
 * Logged-in users are redirected past this in the router guard.
 *
 * Theming: the "Observatory" direction — deep-space hero + warm paper
 * content sections. Tokens are scoped to .landing so nothing leaks into
 * the rest of the app. Art in /images/landing/ is generated by
 * scripts/_gen_landing_assets.js (RFab image API).
 */
export default {
    name: 'LandingView',
    data() {
        return {
            reducedMotion: window.matchMedia('(prefers-reduced-motion: reduce)')
                .matches
        };
    },
    mounted() {
        // The observer drives the section fade-ups; content is visible
        // without JS or with reduced motion.
        if (!this.reducedMotion && 'IntersectionObserver' in window) {
            this.observer = new IntersectionObserver(
                (entries) => {
                    entries.forEach((entry) => {
                        if (entry.isIntersecting) {
                            entry.target.classList.add('is-visible');
                            this.observer.unobserve(entry.target);
                        }
                    });
                },
                { threshold: 0.15 }
            );
            this.$el
                .querySelectorAll('.reveal')
                .forEach((el) => this.observer.observe(el));
        } else {
            this.$el
                .querySelectorAll('.reveal')
                .forEach((el) => el.classList.add('is-visible'));
        }
    },
    beforeUnmount() {
        if (this.observer) this.observer.disconnect();
    }
};
</script>

<template>
    <div class="landing">
        <!-- ============ HERO ============ -->
        <section class="hero">
            <video
                v-if="!reducedMotion"
                class="hero-media"
                autoplay
                muted
                loop
                playsinline
                poster="/images/landing/hero.webp"
                aria-hidden="true"
            >
                <source src="/images/landing/hero-loop.mp4" type="video/mp4" />
            </video>
            <img
                v-else
                class="hero-media"
                src="/images/landing/hero.webp"
                alt=""
                aria-hidden="true"
            />
            <div class="hero-scrim"></div>

            <div class="hero-content container">
                <p class="hero-kicker">
                    Parrhesia &middot; The Collins Institute
                </p>
                <h1 class="hero-title">
                    All of human knowledge,<br />
                    <span class="hero-title-glow">one map.</span>
                </h1>
                <p class="hero-sub">
                    A free skill tree of everything worth learning. Explore it,
                    master skills with an AI tutor at your side, and light up
                    your own path — whether you're nine or ninety.
                </p>
                <div class="hero-ctas">
                    <RouterLink to="/skill-tree" class="btn cta-primary">
                        Explore the skill tree
                    </RouterLink>
                    <RouterLink to="/student-signup" class="btn cta-ghost">
                        Create a free account
                    </RouterLink>
                </div>
                <p class="hero-trust">
                    No ads. Built for self-motivated learners of every age.
                </p>
            </div>

            <div class="hero-fade" aria-hidden="true"></div>
        </section>

        <!-- ============ HOW IT WORKS ============ -->
        <section class="section how-it-works">
            <div class="container">
                <h2 class="section-title reveal">How it works</h2>
                <div class="row g-4">
                    <div class="col-md-4 reveal" style="--reveal-delay: 0s">
                        <div class="step-card">
                            <div class="step-num">1</div>
                            <h3>Find your star</h3>
                            <p>
                                Search the tree or wander it. Every node is a
                                real skill — from long division to quantum
                                mechanics — connected to everything it unlocks.
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4 reveal" style="--reveal-delay: 0.1s">
                        <div class="step-card">
                            <div class="step-num">2</div>
                            <h3>Learn it, prove it</h3>
                            <p>
                                Each skill gathers the best resources on the
                                subject, plus an AI tutor to answer questions
                                and assessments to prove mastery.
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4 reveal" style="--reveal-delay: 0.2s">
                        <div class="step-card">
                            <div class="step-num">3</div>
                            <h3>Light it up</h3>
                            <p>
                                Mastered skills glow gold on your map and open
                                the branches beyond them. Your tree becomes a
                                record of everything you truly know.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ============ FEATURES ============ -->
        <section class="section features">
            <div class="container">
                <div class="feature-row row align-items-center g-5 reveal">
                    <div class="col-lg-6">
                        <img
                            src="/images/landing/feature-tree.webp"
                            alt="A glowing constellation of connected skills, one node blooming gold as it is unlocked"
                            class="feature-art"
                            loading="lazy"
                        />
                    </div>
                    <div class="col-lg-6">
                        <h2>A living map of knowledge</h2>
                        <p>
                            Most sites teach you courses. Parrhesia shows you
                            the territory: thousands of skills linked by what
                            depends on what, so you always know why you're
                            learning something and what it opens next.
                        </p>
                        <RouterLink to="/skill-tree" class="learn-link">
                            See the whole tree →
                        </RouterLink>
                    </div>
                </div>

                <div
                    class="feature-row row align-items-center g-5 flex-lg-row-reverse reveal"
                >
                    <div class="col-lg-6">
                        <img
                            src="/images/landing/feature-tutor.webp"
                            alt="A friendly glowing orb tutor helping a student with holographic diagrams"
                            class="feature-art"
                            loading="lazy"
                        />
                    </div>
                    <div class="col-lg-6">
                        <h2>A tutor on every skill</h2>
                        <p>
                            Stuck at 11pm on a concept nobody around you
                            understands? Every skill has an AI tutor that
                            explains, quizzes, and marks your work — patient
                            with an eight-year-old, rigorous with a researcher.
                        </p>
                        <RouterLink to="/search" class="learn-link">
                            Find a skill to try →
                        </RouterLink>
                    </div>
                </div>

                <div class="feature-row row align-items-center g-5 reveal">
                    <div class="col-lg-6">
                        <img
                            src="/images/landing/feature-tracks.webp"
                            alt="A glowing path of stepping stones rising through floating islands of subjects"
                            class="feature-art"
                            loading="lazy"
                        />
                    </div>
                    <div class="col-lg-6">
                        <h2>Tracks when you want a guide</h2>
                        <p>
                            Prefer a path to a map? Learning tracks chain
                            skills into guided journeys — a route through
                            mathematics, a grand tour of history — with
                            milestones to keep you moving.
                        </p>
                        <RouterLink to="/learning-tracks" class="learn-link">
                            Browse learning tracks →
                        </RouterLink>
                    </div>
                </div>
            </div>
        </section>

        <!-- ============ FOR EVERYONE ============ -->
        <section class="section everyone">
            <div class="container">
                <h2 class="section-title reveal">One tree, every learner</h2>
                <div class="reveal">
                    <img
                        src="/images/landing/feature-everyone.webp"
                        alt="A child, a teenager, and an adult each exploring their own glowing tree of knowledge"
                        class="everyone-art"
                        loading="lazy"
                    />
                </div>
                <div class="row g-4 everyone-cards">
                    <div class="col-md-4 reveal" style="--reveal-delay: 0s">
                        <div class="audience-card">
                            <h3>Kids &amp; families</h3>
                            <p>
                                Kids don't need cartoons to love learning —
                                they need to see progress. The glowing map
                                makes mastery visible, and parents can follow
                                along.
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4 reveal" style="--reveal-delay: 0.1s">
                        <div class="audience-card">
                            <h3>Self-taught adults</h3>
                            <p>
                                Fill the gaps a degree left, or start a field
                                from zero. The tree shows honest prerequisites,
                                so you never build on sand.
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4 reveal" style="--reveal-delay: 0.2s">
                        <div class="audience-card">
                            <h3>Schools &amp; instructors</h3>
                            <p>
                                Cohorts, dashboards, and assessment tools for
                                classrooms that want self-paced mastery
                                learning without losing sight of anyone.
                            </p>
                            <RouterLink
                                to="/instructor-signup"
                                class="learn-link"
                            >
                                Instructor sign-up →
                            </RouterLink>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ============ FINAL CTA ============ -->
        <section class="final-cta">
            <div class="container reveal">
                <h2>Ready to light your first star?</h2>
                <p>
                    We do not educate; we facilitate education. The map is
                    free — the climbing is yours.
                </p>
                <div class="hero-ctas">
                    <RouterLink to="/student-signup" class="btn cta-primary">
                        Start learning free
                    </RouterLink>
                    <RouterLink to="/skill-tree" class="btn cta-ghost">
                        Just explore first
                    </RouterLink>
                </div>
            </div>
        </section>
    </div>
</template>

<style scoped>
/* ============ Observatory theme tokens (scoped to the landing page) ==== */
.landing {
    --ci-space: #0d1030;
    --ci-space-2: #191650;
    --ci-purple: #5f31dd;
    --ci-purple-soft: #7c5cf0;
    --ci-cyan: #45d8e2;
    --ci-gold: #ffc857;
    --ci-paper: #faf9ff;
    --ci-ink: #221c3f;
    --ci-ink-soft: #4c4570;

    font-family: 'Poppins', sans-serif;
    color: var(--ci-ink);
    background-color: var(--ci-paper);
    overflow-x: hidden;
}

.landing h1,
.landing h2,
.landing h3 {
    font-family: 'Poppins', sans-serif;
}

/* ============ Hero ============ */
.hero {
    position: relative;
    min-height: 92vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: var(--ci-space);
    overflow: hidden;
}

.hero-media {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: center;
}

.hero-scrim {
    position: absolute;
    inset: 0;
    background: linear-gradient(
        180deg,
        rgba(13, 16, 48, 0.55) 0%,
        rgba(13, 16, 48, 0.25) 40%,
        rgba(13, 16, 48, 0.75) 100%
    );
}

.hero-content {
    position: relative;
    z-index: 1;
    text-align: center;
    padding-top: 110px; /* clears the fixed navbar */
    padding-bottom: 60px;
    max-width: 860px;
}

.hero-kicker {
    color: var(--ci-cyan);
    font-weight: 600;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    font-size: 0.85rem;
    margin-bottom: 14px;
}

.hero-title {
    color: white;
    font-weight: 900;
    font-size: clamp(2.4rem, 6vw, 4.2rem);
    line-height: 1.08;
    margin-bottom: 20px;
    text-shadow: 0 4px 30px rgba(13, 16, 48, 0.8);
}

.hero-title-glow {
    background: linear-gradient(90deg, var(--ci-cyan), var(--ci-gold));
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
}

.hero-sub {
    color: rgba(255, 255, 255, 0.88);
    font-size: clamp(1.05rem, 2vw, 1.3rem);
    line-height: 1.6;
    max-width: 640px;
    margin: 0 auto 32px;
}

.hero-ctas {
    display: flex;
    gap: 14px;
    justify-content: center;
    flex-wrap: wrap;
}

.cta-primary {
    background: linear-gradient(
        135deg,
        var(--ci-purple),
        var(--ci-purple-soft)
    );
    color: white !important;
    font-weight: 600;
    font-size: 1.05rem;
    padding: 12px 30px;
    border-radius: 999px;
    border: none;
    box-shadow: 0 6px 24px rgba(95, 49, 221, 0.45);
    transition:
        transform 0.15s ease,
        box-shadow 0.15s ease;
}

.cta-primary:hover,
.cta-primary:focus {
    transform: translateY(-2px);
    box-shadow: 0 10px 32px rgba(95, 49, 221, 0.6);
    color: white;
}

.cta-ghost {
    color: white !important;
    font-weight: 600;
    font-size: 1.05rem;
    padding: 12px 30px;
    border-radius: 999px;
    border: 2px solid rgba(255, 255, 255, 0.55);
    background: rgba(255, 255, 255, 0.06);
    backdrop-filter: blur(4px);
    transition:
        border-color 0.15s ease,
        background 0.15s ease;
}

.cta-ghost:hover,
.cta-ghost:focus {
    border-color: var(--ci-cyan);
    background: rgba(69, 216, 226, 0.12);
    color: white;
}

.hero-trust {
    color: rgba(255, 255, 255, 0.6);
    font-size: 0.9rem;
    margin-top: 22px;
}

.hero-fade {
    position: absolute;
    left: 0;
    right: 0;
    bottom: -1px;
    height: 110px;
    background: linear-gradient(180deg, transparent, var(--ci-paper));
    z-index: 1;
}

/* ============ Sections ============ */
.section {
    padding: 80px 0;
}

.section-title {
    text-align: center;
    font-weight: 900;
    font-size: clamp(1.8rem, 4vw, 2.6rem);
    color: var(--ci-ink);
    margin-bottom: 48px;
}

/* How it works */
.how-it-works {
    padding-top: 30px;
}

.step-card {
    background: white;
    border-radius: 20px;
    padding: 32px 28px;
    height: 100%;
    border: 1px solid rgba(95, 49, 221, 0.12);
    box-shadow: 0 8px 30px rgba(34, 28, 63, 0.06);
    transition:
        transform 0.2s ease,
        box-shadow 0.2s ease;
}

.step-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 14px 40px rgba(34, 28, 63, 0.1);
}

.step-num {
    width: 44px;
    height: 44px;
    border-radius: 50%;
    background: linear-gradient(135deg, var(--ci-purple), var(--ci-cyan));
    color: white;
    font-weight: 900;
    font-size: 1.2rem;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 18px;
}

.step-card h3 {
    font-weight: 700;
    font-size: 1.25rem;
    margin-bottom: 10px;
}

.step-card p {
    color: var(--ci-ink-soft);
    line-height: 1.65;
    margin: 0;
}

/* Features */
.feature-row {
    margin-bottom: 70px;
}

.feature-row:last-child {
    margin-bottom: 0;
}

.feature-art {
    width: 100%;
    border-radius: 24px;
    box-shadow: 0 18px 60px rgba(13, 16, 48, 0.25);
}

.features h2 {
    font-weight: 900;
    font-size: clamp(1.6rem, 3vw, 2.2rem);
    margin-bottom: 16px;
    color: var(--ci-ink);
}

.features p {
    color: var(--ci-ink-soft);
    font-size: 1.05rem;
    line-height: 1.7;
}

.learn-link {
    color: var(--ci-purple);
    font-weight: 600;
    text-decoration: none;
}

.learn-link:hover {
    color: var(--ci-purple-soft);
    text-decoration: underline;
}

/* Everyone */
.everyone {
    background: linear-gradient(180deg, var(--ci-paper), #efeafd);
}

.everyone-art {
    display: block;
    width: 100%;
    max-width: 980px;
    margin: 0 auto 48px;
    border-radius: 24px;
    box-shadow: 0 18px 60px rgba(13, 16, 48, 0.25);
}

.audience-card {
    background: white;
    border-radius: 20px;
    padding: 28px;
    height: 100%;
    border: 1px solid rgba(95, 49, 221, 0.12);
    box-shadow: 0 8px 30px rgba(34, 28, 63, 0.06);
}

.audience-card h3 {
    font-weight: 700;
    font-size: 1.2rem;
    margin-bottom: 10px;
}

.audience-card p {
    color: var(--ci-ink-soft);
    line-height: 1.65;
}

/* Final CTA */
.final-cta {
    background:
        radial-gradient(
            ellipse at 50% 120%,
            rgba(95, 49, 221, 0.5),
            transparent 60%
        ),
        var(--ci-space);
    text-align: center;
    padding: 90px 0;
}

.final-cta h2 {
    color: white;
    font-weight: 900;
    font-size: clamp(1.8rem, 4vw, 2.6rem);
    margin-bottom: 14px;
}

.final-cta p {
    color: rgba(255, 255, 255, 0.75);
    font-size: 1.1rem;
    margin-bottom: 32px;
}

/* ============ Reveal-on-scroll ============ */
.reveal {
    opacity: 0;
    transform: translateY(24px);
    transition:
        opacity 0.6s ease,
        transform 0.6s ease;
    transition-delay: var(--reveal-delay, 0s);
}

.reveal.is-visible {
    opacity: 1;
    transform: none;
}

@media (prefers-reduced-motion: reduce) {
    .reveal {
        opacity: 1;
        transform: none;
        transition: none;
    }
}
</style>
