<script>
/**
 * MascotLoop — the Institute's themed loading mascot (the observatory's
 * solarpunk neko astronomer), per the loading-FX rulebook: long waits get a
 * mascot clip, never a bare spinner. Delay-gated so near-instant waits never
 * flash it. Clips live in /images/loading/<slug>-loop.mp4 with a matching
 * .jpg poster (generated by scripts/_gen_observatory_ui_assets.js +
 * _gen_observatory_loops.js).
 */
export default {
    props: {
        // mascot-tutor | mascot-wait | mascot-test
        slug: { type: String, default: 'mascot-wait' },
        message: { type: String, default: '' },
        size: { type: String, default: '220px' }
    },
    data() {
        return {
            // Reduced-motion users get the still poster, not the loop.
            animate: !window.matchMedia('(prefers-reduced-motion: reduce)')
                .matches
        };
    }
};
</script>

<template>
    <div class="mascot-loop" :style="{ '--mascot-size': size }">
        <video
            :src="animate ? `/images/loading/${slug}-loop.mp4` : undefined"
            :poster="`/images/loading/${slug}.jpg`"
            :autoplay="animate"
            muted
            loop
            playsinline
            aria-hidden="true"
        ></video>
        <div v-if="message" class="mascot-message" role="status">
            {{ message }}
        </div>
    </div>
</template>

<style scoped>
.mascot-loop {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
    /* Delay gate: invisible for 0.2s so instant loads never flash it. */
    animation: obsFadeIn 0.15s ease 0.2s backwards;
}

.mascot-loop video {
    width: var(--mascot-size);
    height: var(--mascot-size);
    object-fit: cover;
    border-radius: 50%;
    border: 1px solid var(--obs-line-strong, rgba(124, 92, 240, 0.6));
    box-shadow: 0 0 30px rgba(95, 49, 221, 0.45),
        inset 0 0 30px rgba(13, 16, 48, 0.6);
}

.mascot-message {
    color: var(--obs-ink, #e8e6ff);
    font-size: 15px;
    letter-spacing: 0.4px;
    text-align: center;
}

@media (prefers-reduced-motion: reduce) {
    .mascot-loop video {
        /* Poster-like: pause visual churn for reduced-motion users. */
        filter: none;
    }
}
</style>
